// Comprehensive Training Data for NLP Service
// This file contains extensive training datasets for better classification performance

export const categoryTrainingData = [
    // MEETING CATEGORY - 50+ examples
    { text: 'meeting with team', category: 'meeting' },
    { text: 'call with client', category: 'meeting' },
    { text: 'conference call', category: 'meeting' },
    { text: 'standup meeting', category: 'meeting' },
    { text: 'one on one with manager', category: 'meeting' },
    { text: 'team sync', category: 'meeting' },
    { text: 'client presentation', category: 'meeting' },
    { text: 'interview', category: 'meeting' },
    { text: 'board meeting', category: 'meeting' },
    { text: 'staff meeting', category: 'meeting' },
    { text: 'project kickoff', category: 'meeting' },
    { text: 'retrospective meeting', category: 'meeting' },
    { text: 'planning session', category: 'meeting' },
    { text: 'review meeting', category: 'meeting' },
    { text: 'all hands meeting', category: 'meeting' },
    { text: 'department meeting', category: 'meeting' },
    { text: 'client call', category: 'meeting' },
    { text: 'video conference', category: 'meeting' },
    { text: 'zoom meeting', category: 'meeting' },
    { text: 'teams meeting', category: 'meeting' },
    { text: 'google meet', category: 'meeting' },
    { text: 'skype call', category: 'meeting' },
    { text: 'phone call', category: 'meeting' },
    { text: 'conference', category: 'meeting' },
    { text: 'seminar', category: 'meeting' },
    { text: 'workshop', category: 'meeting' },
    { text: 'training session', category: 'meeting' },
    { text: 'demo', category: 'meeting' },
    { text: 'pitch meeting', category: 'meeting' },
    { text: 'sales call', category: 'meeting' },
    { text: 'customer meeting', category: 'meeting' },
    { text: 'vendor meeting', category: 'meeting' },
    { text: 'partner meeting', category: 'meeting' },
    { text: 'stakeholder meeting', category: 'meeting' },
    { text: 'executive meeting', category: 'meeting' },
    { text: 'management meeting', category: 'meeting' },
    { text: 'team building', category: 'meeting' },
    { text: 'lunch meeting', category: 'meeting' },
    { text: 'coffee meeting', category: 'meeting' },
    { text: 'breakfast meeting', category: 'meeting' },
    { text: 'dinner meeting', category: 'meeting' },
    { text: 'networking event', category: 'meeting' },
    { text: 'appointment', category: 'meeting' },
    { text: 'consultation', category: 'meeting' },
    { text: 'discussion', category: 'meeting' },
    { text: 'brainstorming', category: 'meeting' },
    { text: 'sync up', category: 'meeting' },
    { text: 'catch up', category: 'meeting' },
    { text: 'touch base', category: 'meeting' },
    { text: 'check in', category: 'meeting' },

    // WORK CATEGORY - 50+ examples
    { text: 'work on project', category: 'work' },
    { text: 'deadline for report', category: 'work' },
    { text: 'project review', category: 'work' },
    { text: 'code review', category: 'work' },
    { text: 'write documentation', category: 'work' },
    { text: 'debug issue', category: 'work' },
    { text: 'deploy to production', category: 'work' },
    { text: 'research new technology', category: 'work' },
    { text: 'develop feature', category: 'work' },
    { text: 'fix bug', category: 'work' },
    { text: 'implement solution', category: 'work' },
    { text: 'create design', category: 'work' },
    { text: 'update system', category: 'work' },
    { text: 'optimize performance', category: 'work' },
    { text: 'test application', category: 'work' },
    { text: 'build prototype', category: 'work' },
    { text: 'analyze data', category: 'work' },
    { text: 'create report', category: 'work' },
    { text: 'prepare presentation', category: 'work' },
    { text: 'submit proposal', category: 'work' },
    { text: 'review contract', category: 'work' },
    { text: 'update database', category: 'work' },
    { text: 'configure server', category: 'work' },
    { text: 'setup environment', category: 'work' },
    { text: 'backup data', category: 'work' },
    { text: 'migrate system', category: 'work' },
    { text: 'install software', category: 'work' },
    { text: 'update dependencies', category: 'work' },
    { text: 'refactor code', category: 'work' },
    { text: 'write tests', category: 'work' },
    { text: 'run tests', category: 'work' },
    { text: 'deploy application', category: 'work' },
    { text: 'monitor system', category: 'work' },
    { text: 'troubleshoot issue', category: 'work' },
    { text: 'resolve conflict', category: 'work' },
    { text: 'merge branches', category: 'work' },
    { text: 'commit changes', category: 'work' },
    { text: 'push code', category: 'work' },
    { text: 'pull request', category: 'work' },
    { text: 'code cleanup', category: 'work' },
    { text: 'performance tuning', category: 'work' },
    { text: 'security audit', category: 'work' },
    { text: 'compliance check', category: 'work' },
    { text: 'documentation update', category: 'work' },
    { text: 'user training', category: 'work' },
    { text: 'system maintenance', category: 'work' },
    { text: 'backup verification', category: 'work' },
    { text: 'disaster recovery', category: 'work' },
    { text: 'capacity planning', category: 'work' },

    // PERSONAL CATEGORY - 50+ examples
    { text: 'buy groceries', category: 'personal' },
    { text: 'go to gym', category: 'personal' },
    { text: 'shopping', category: 'personal' },
    { text: 'doctor appointment', category: 'personal' },
    { text: 'dentist visit', category: 'personal' },
    { text: 'haircut', category: 'personal' },
    { text: 'car maintenance', category: 'personal' },
    { text: 'bank visit', category: 'personal' },
    { text: 'post office', category: 'personal' },
    { text: 'pharmacy', category: 'personal' },
    { text: 'grocery shopping', category: 'personal' },
    { text: 'clothes shopping', category: 'personal' },
    { text: 'gift shopping', category: 'personal' },
    { text: 'exercise', category: 'personal' },
    { text: 'workout', category: 'personal' },
    { text: 'running', category: 'personal' },
    { text: 'swimming', category: 'personal' },
    { text: 'yoga', category: 'personal' },
    { text: 'pilates', category: 'personal' },
    { text: 'cycling', category: 'personal' },
    { text: 'hiking', category: 'personal' },
    { text: 'walking', category: 'personal' },
    { text: 'medical checkup', category: 'personal' },
    { text: 'eye exam', category: 'personal' },
    { text: 'dental cleaning', category: 'personal' },
    { text: 'therapy session', category: 'personal' },
    { text: 'massage', category: 'personal' },
    { text: 'spa appointment', category: 'personal' },
    { text: 'manicure', category: 'personal' },
    { text: 'pedicure', category: 'personal' },
    { text: 'car wash', category: 'personal' },
    { text: 'oil change', category: 'personal' },
    { text: 'tire rotation', category: 'personal' },
    { text: 'car inspection', category: 'personal' },
    { text: 'dmv visit', category: 'personal' },
    { text: 'license renewal', category: 'personal' },
    { text: 'insurance claim', category: 'personal' },
    { text: 'tax preparation', category: 'personal' },
    { text: 'bill payment', category: 'personal' },
    { text: 'utility setup', category: 'personal' },
    { text: 'internet installation', category: 'personal' },
    { text: 'cable setup', category: 'personal' },
    { text: 'home maintenance', category: 'personal' },
    { text: 'cleaning', category: 'personal' },
    { text: 'laundry', category: 'personal' },
    { text: 'cooking', category: 'personal' },
    { text: 'meal prep', category: 'personal' },
    { text: 'family time', category: 'personal' },
    { text: 'date night', category: 'personal' },

    // STUDY CATEGORY - 50+ examples
    { text: 'study for exam', category: 'study' },
    { text: 'read book', category: 'study' },
    { text: 'learn new skill', category: 'study' },
    { text: 'online course', category: 'study' },
    { text: 'practice coding', category: 'study' },
    { text: 'research topic', category: 'study' },
    { text: 'homework', category: 'study' },
    { text: 'prepare presentation', category: 'study' },
    { text: 'write essay', category: 'study' },
    { text: 'complete assignment', category: 'study' },
    { text: 'review notes', category: 'study' },
    { text: 'prepare for test', category: 'study' },
    { text: 'take practice exam', category: 'study' },
    { text: 'watch tutorial', category: 'study' },
    { text: 'read article', category: 'study' },
    { text: 'listen to podcast', category: 'study' },
    { text: 'attend webinar', category: 'study' },
    { text: 'join workshop', category: 'study' },
    { text: 'take course', category: 'study' },
    { text: 'learn language', category: 'study' },
    { text: 'practice instrument', category: 'study' },
    { text: 'art class', category: 'study' },
    { text: 'music lesson', category: 'study' },
    { text: 'dance class', category: 'study' },
    { text: 'cooking class', category: 'study' },
    { text: 'photography workshop', category: 'study' },
    { text: 'writing workshop', category: 'study' },
    { text: 'coding bootcamp', category: 'study' },
    { text: 'certification prep', category: 'study' },
    { text: 'license exam', category: 'study' },
    { text: 'professional development', category: 'study' },
    { text: 'skill building', category: 'study' },
    { text: 'knowledge update', category: 'study' },
    { text: 'industry research', category: 'study' },
    { text: 'market analysis', category: 'study' },
    { text: 'competitor analysis', category: 'study' },
    { text: 'trend research', category: 'study' },
    { text: 'case study', category: 'study' },
    { text: 'literature review', category: 'study' },
    { text: 'academic reading', category: 'study' },
    { text: 'thesis work', category: 'study' },
    { text: 'dissertation', category: 'study' },
    { text: 'research paper', category: 'study' },
    { text: 'data analysis', category: 'study' },
    { text: 'statistical analysis', category: 'study' },
    { text: 'experiment design', category: 'study' },
    { text: 'lab work', category: 'study' },
    { text: 'field research', category: 'study' },
    { text: 'survey design', category: 'study' }
];

export const priorityTrainingData = [
    // URGENT PRIORITY - 40+ examples
    { text: 'urgent task', priority: 'urgent' },
    { text: 'asap meeting', priority: 'urgent' },
    { text: 'critical deadline', priority: 'urgent' },
    { text: 'emergency call', priority: 'urgent' },
    { text: 'immediate action required', priority: 'urgent' },
    { text: 'deadline today', priority: 'urgent' },
    { text: 'fix production bug', priority: 'urgent' },
    { text: 'client emergency', priority: 'urgent' },
    { text: 'system down', priority: 'urgent' },
    { text: 'security breach', priority: 'urgent' },
    { text: 'data loss', priority: 'urgent' },
    { text: 'server crash', priority: 'urgent' },
    { text: 'website down', priority: 'urgent' },
    { text: 'payment issue', priority: 'urgent' },
    { text: 'customer complaint', priority: 'urgent' },
    { text: 'legal issue', priority: 'urgent' },
    { text: 'compliance violation', priority: 'urgent' },
    { text: 'audit finding', priority: 'urgent' },
    { text: 'regulatory issue', priority: 'urgent' },
    { text: 'safety concern', priority: 'urgent' },
    { text: 'incident response', priority: 'urgent' },
    { text: 'crisis management', priority: 'urgent' },
    { text: 'damage control', priority: 'urgent' },
    { text: 'hotfix', priority: 'urgent' },
    { text: 'patch deployment', priority: 'urgent' },
    { text: 'rollback', priority: 'urgent' },
    { text: 'recovery', priority: 'urgent' },
    { text: 'restoration', priority: 'urgent' },
    { text: 'escalation', priority: 'urgent' },
    { text: 'priority one', priority: 'urgent' },
    { text: 'p1 issue', priority: 'urgent' },
    { text: 'severity 1', priority: 'urgent' },
    { text: 'critical path', priority: 'urgent' },
    { text: 'blocking issue', priority: 'urgent' },
    { text: 'show stopper', priority: 'urgent' },
    { text: 'must fix', priority: 'urgent' },
    { text: 'cannot wait', priority: 'urgent' },
    { text: 'time sensitive', priority: 'urgent' },
    { text: 'expires today', priority: 'urgent' },
    { text: 'due immediately', priority: 'urgent' },

    // HIGH PRIORITY - 40+ examples
    { text: 'high priority', priority: 'high' },
    { text: 'important meeting', priority: 'high' },
    { text: 'key project', priority: 'high' },
    { text: 'deadline tomorrow', priority: 'high' },
    { text: 'client presentation', priority: 'high' },
    { text: 'review code', priority: 'high' },
    { text: 'prepare report', priority: 'high' },
    { text: 'team meeting', priority: 'high' },
    { text: 'strategic planning', priority: 'high' },
    { text: 'budget review', priority: 'high' },
    { text: 'quarterly review', priority: 'high' },
    { text: 'performance review', priority: 'high' },
    { text: 'project milestone', priority: 'high' },
    { text: 'deliverable', priority: 'high' },
    { text: 'stakeholder update', priority: 'high' },
    { text: 'executive briefing', priority: 'high' },
    { text: 'board presentation', priority: 'high' },
    { text: 'investor meeting', priority: 'high' },
    { text: 'partnership discussion', priority: 'high' },
    { text: 'contract negotiation', priority: 'high' },
    { text: 'vendor selection', priority: 'high' },
    { text: 'technology evaluation', priority: 'high' },
    { text: 'architecture review', priority: 'high' },
    { text: 'design review', priority: 'high' },
    { text: 'security review', priority: 'high' },
    { text: 'compliance check', priority: 'high' },
    { text: 'quality assurance', priority: 'high' },
    { text: 'testing phase', priority: 'high' },
    { text: 'deployment planning', priority: 'high' },
    { text: 'go live preparation', priority: 'high' },
    { text: 'user acceptance', priority: 'high' },
    { text: 'training delivery', priority: 'high' },
    { text: 'documentation review', priority: 'high' },
    { text: 'process improvement', priority: 'high' },
    { text: 'efficiency optimization', priority: 'high' },
    { text: 'cost reduction', priority: 'high' },
    { text: 'revenue generation', priority: 'high' },
    { text: 'market expansion', priority: 'high' },
    { text: 'competitive analysis', priority: 'high' },
    { text: 'customer satisfaction', priority: 'high' },

    // LOW PRIORITY - 40+ examples
    { text: 'low priority task', priority: 'low' },
    { text: 'whenever possible', priority: 'low' },
    { text: 'sometime this week', priority: 'low' },
    { text: 'nice to have', priority: 'low' },
    { text: 'optional task', priority: 'low' },
    { text: 'when you have time', priority: 'low' },
    { text: 'background work', priority: 'low' },
    { text: 'research project', priority: 'low' },
    { text: 'exploration', priority: 'low' },
    { text: 'experimentation', priority: 'low' },
    { text: 'proof of concept', priority: 'low' },
    { text: 'prototype', priority: 'low' },
    { text: 'draft version', priority: 'low' },
    { text: 'rough outline', priority: 'low' },
    { text: 'initial thoughts', priority: 'low' },
    { text: 'brainstorming', priority: 'low' },
    { text: 'ideation', priority: 'low' },
    { text: 'creative thinking', priority: 'low' },
    { text: 'innovation', priority: 'low' },
    { text: 'future planning', priority: 'low' },
    { text: 'long term', priority: 'low' },
    { text: 'strategic thinking', priority: 'low' },
    { text: 'vision planning', priority: 'low' },
    { text: 'roadmap', priority: 'low' },
    { text: 'blue sky', priority: 'low' },
    { text: 'wishlist', priority: 'low' },
    { text: 'backlog', priority: 'low' },
    { text: 'deferred', priority: 'low' },
    { text: 'postponed', priority: 'low' },
    { text: 'delayed', priority: 'low' },
    { text: 'someday', priority: 'low' },
    { text: 'eventually', priority: 'low' },
    { text: 'if time permits', priority: 'low' },
    { text: 'bonus work', priority: 'low' },
    { text: 'extra credit', priority: 'low' },
    { text: 'side project', priority: 'low' },
    { text: 'hobby', priority: 'low' },
    { text: 'personal interest', priority: 'low' },
    { text: 'leisure activity', priority: 'low' },
    { text: 'recreational', priority: 'low' }
];

export const durationPatterns = [
    // Hours patterns
    { pattern: /(\d+)\s*hours?/gi, multiplier: 60 },
    { pattern: /(\d+)\s*hrs?/gi, multiplier: 60 },
    { pattern: /(\d+)\s*h/gi, multiplier: 60 },
    { pattern: /(\d+)\s*hour/gi, multiplier: 60 },
    { pattern: /(\d+)\s*hr/gi, multiplier: 60 },
    { pattern: /(\d+)\s*hr\./gi, multiplier: 60 },
    { pattern: /(\d+)\s*h\./gi, multiplier: 60 },
    
    // Minutes patterns
    { pattern: /(\d+)\s*minutes?/gi, multiplier: 1 },
    { pattern: /(\d+)\s*mins?/gi, multiplier: 1 },
    { pattern: /(\d+)\s*min/gi, multiplier: 1 },
    { pattern: /(\d+)\s*m/gi, multiplier: 1 },
    { pattern: /(\d+)\s*minute/gi, multiplier: 1 },
    { pattern: /(\d+)\s*min\./gi, multiplier: 1 },
    { pattern: /(\d+)\s*m\./gi, multiplier: 1 },
    
    // Days patterns
    { pattern: /(\d+)\s*days?/gi, multiplier: 1440 },
    { pattern: /(\d+)\s*d/gi, multiplier: 1440 },
    { pattern: /(\d+)\s*day/gi, multiplier: 1440 },
    { pattern: /(\d+)\s*d\./gi, multiplier: 1440 },
    
    // Weeks patterns
    { pattern: /(\d+)\s*weeks?/gi, multiplier: 10080 },
    { pattern: /(\d+)\s*wks?/gi, multiplier: 10080 },
    { pattern: /(\d+)\s*w/gi, multiplier: 10080 },
    { pattern: /(\d+)\s*week/gi, multiplier: 10080 },
    { pattern: /(\d+)\s*wk\./gi, multiplier: 10080 },
    { pattern: /(\d+)\s*w\./gi, multiplier: 10080 },
    
    // Common duration phrases
    { pattern: /half\s*an?\s*hour/gi, multiplier: 30 },
    { pattern: /quarter\s*of\s*an?\s*hour/gi, multiplier: 15 },
    { pattern: /three\s*quarters?\s*of\s*an?\s*hour/gi, multiplier: 45 },
    { pattern: /one\s*and\s*half\s*hours?/gi, multiplier: 90 },
    { pattern: /two\s*and\s*half\s*hours?/gi, multiplier: 150 },
    { pattern: /three\s*and\s*half\s*hours?/gi, multiplier: 210 },
    { pattern: /four\s*and\s*half\s*hours?/gi, multiplier: 270 },
    { pattern: /five\s*and\s*half\s*hours?/gi, multiplier: 330 },
    { pattern: /six\s*and\s*half\s*hours?/gi, multiplier: 390 },
    { pattern: /seven\s*and\s*half\s*hours?/gi, multiplier: 450 },
    { pattern: /eight\s*and\s*half\s*hours?/gi, multiplier: 510 },
    { pattern: /nine\s*and\s*half\s*hours?/gi, multiplier: 570 },
    { pattern: /ten\s*and\s*half\s*hours?/gi, multiplier: 630 },
    
    // Time ranges
    { pattern: /(\d+)\s*to\s*(\d+)\s*hours?/gi, multiplier: 60, range: true },
    { pattern: /(\d+)\s*-\s*(\d+)\s*hours?/gi, multiplier: 60, range: true },
    { pattern: /(\d+)\s*to\s*(\d+)\s*minutes?/gi, multiplier: 1, range: true },
    { pattern: /(\d+)\s*-\s*(\d+)\s*minutes?/gi, multiplier: 1, range: true },
    
    // Business hours
    { pattern: /full\s*day/gi, multiplier: 480 },
    { pattern: /half\s*day/gi, multiplier: 240 },
    { pattern: /business\s*day/gi, multiplier: 480 },
    { pattern: /work\s*day/gi, multiplier: 480 },
    { pattern: /working\s*day/gi, multiplier: 480 },
    
    // Common time expressions
    { pattern: /brief/gi, multiplier: 15 },
    { pattern: /quick/gi, multiplier: 15 },
    { pattern: /short/gi, multiplier: 30 },
    { pattern: /long/gi, multiplier: 120 },
    { pattern: /extended/gi, multiplier: 180 },
    { pattern: /all\s*day/gi, multiplier: 480 },
    { pattern: /all\s*night/gi, multiplier: 480 },
    { pattern: /overnight/gi, multiplier: 480 },
    { pattern: /weekend/gi, multiplier: 1440 },
    { pattern: /week\s*long/gi, multiplier: 10080 }
];

export const recurrencePatterns = [
    // Daily patterns
    { pattern: /daily/gi, freq: 'DAILY', interval: 1 },
    { pattern: /every\s*day/gi, freq: 'DAILY', interval: 1 },
    { pattern: /each\s*day/gi, freq: 'DAILY', interval: 1 },
    { pattern: /day\s*by\s*day/gi, freq: 'DAILY', interval: 1 },
    { pattern: /every\s*(\d+)\s*days?/gi, freq: 'DAILY', interval: 'dynamic' },
    { pattern: /every\s*other\s*day/gi, freq: 'DAILY', interval: 2 },
    { pattern: /alternate\s*days?/gi, freq: 'DAILY', interval: 2 },
    { pattern: /bi\s*daily/gi, freq: 'DAILY', interval: 1 },
    { pattern: /twice\s*daily/gi, freq: 'DAILY', interval: 1 },
    { pattern: /morning\s*daily/gi, freq: 'DAILY', interval: 1 },
    { pattern: /evening\s*daily/gi, freq: 'DAILY', interval: 1 },
    
    // Weekly patterns
    { pattern: /weekly/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /every\s*week/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /each\s*week/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /week\s*by\s*week/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /every\s*(\d+)\s*weeks?/gi, freq: 'WEEKLY', interval: 'dynamic' },
    { pattern: /bi\s*weekly/gi, freq: 'WEEKLY', interval: 2 },
    { pattern: /every\s*other\s*week/gi, freq: 'WEEKLY', interval: 2 },
    { pattern: /alternate\s*weeks?/gi, freq: 'WEEKLY', interval: 2 },
    { pattern: /twice\s*weekly/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /semi\s*weekly/gi, freq: 'WEEKLY', interval: 1 },
    
    // Specific weekdays
    { pattern: /every\s*monday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO' },
    { pattern: /every\s*tuesday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'TU' },
    { pattern: /every\s*wednesday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'WE' },
    { pattern: /every\s*thursday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'TH' },
    { pattern: /every\s*friday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'FR' },
    { pattern: /every\s*saturday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'SA' },
    { pattern: /every\s*sunday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'SU' },
    { pattern: /mondays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO' },
    { pattern: /tuesdays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'TU' },
    { pattern: /wednesdays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'WE' },
    { pattern: /thursdays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'TH' },
    { pattern: /fridays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'FR' },
    { pattern: /saturdays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'SA' },
    { pattern: /sundays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'SU' },
    
    // Weekday patterns
    { pattern: /weekdays?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /week\s*days?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /business\s*days?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /working\s*days?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /weekends?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'SA,SU' },
    { pattern: /week\s*ends?/gi, freq: 'WEEKLY', interval: 1, byweekday: 'SA,SU' },
    
    // Monthly patterns
    { pattern: /monthly/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /every\s*month/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /each\s*month/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /month\s*by\s*month/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /every\s*(\d+)\s*months?/gi, freq: 'MONTHLY', interval: 'dynamic' },
    { pattern: /bi\s*monthly/gi, freq: 'MONTHLY', interval: 2 },
    { pattern: /every\s*other\s*month/gi, freq: 'MONTHLY', interval: 2 },
    { pattern: /alternate\s*months?/gi, freq: 'MONTHLY', interval: 2 },
    { pattern: /quarterly/gi, freq: 'MONTHLY', interval: 3 },
    { pattern: /every\s*quarter/gi, freq: 'MONTHLY', interval: 3 },
    { pattern: /semi\s*annually/gi, freq: 'MONTHLY', interval: 6 },
    { pattern: /twice\s*yearly/gi, freq: 'MONTHLY', interval: 6 },
    
    // Specific monthly patterns
    { pattern: /first\s*monday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'MO', bysetpos: 1 },
    { pattern: /first\s*tuesday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'TU', bysetpos: 1 },
    { pattern: /first\s*wednesday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'WE', bysetpos: 1 },
    { pattern: /first\s*thursday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'TH', bysetpos: 1 },
    { pattern: /first\s*friday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'FR', bysetpos: 1 },
    { pattern: /last\s*monday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'MO', bysetpos: -1 },
    { pattern: /last\s*tuesday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'TU', bysetpos: -1 },
    { pattern: /last\s*wednesday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'WE', bysetpos: -1 },
    { pattern: /last\s*thursday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'TH', bysetpos: -1 },
    { pattern: /last\s*friday/gi, freq: 'MONTHLY', interval: 1, byweekday: 'FR', bysetpos: -1 },
    
    // Yearly patterns
    { pattern: /yearly/gi, freq: 'YEARLY', interval: 1 },
    { pattern: /annually/gi, freq: 'YEARLY', interval: 1 },
    { pattern: /every\s*year/gi, freq: 'YEARLY', interval: 1 },
    { pattern: /each\s*year/gi, freq: 'YEARLY', interval: 1 },
    { pattern: /year\s*by\s*year/gi, freq: 'YEARLY', interval: 1 },
    { pattern: /every\s*(\d+)\s*years?/gi, freq: 'YEARLY', interval: 'dynamic' },
    { pattern: /bi\s*annually/gi, freq: 'YEARLY', interval: 2 },
    { pattern: /every\s*other\s*year/gi, freq: 'YEARLY', interval: 2 },
    { pattern: /alternate\s*years?/gi, freq: 'YEARLY', interval: 2 },
    
    // Specific yearly patterns
    { pattern: /new\s*year/gi, freq: 'YEARLY', interval: 1, bymonth: 1, bymonthday: 1 },
    { pattern: /christmas/gi, freq: 'YEARLY', interval: 1, bymonth: 12, bymonthday: 25 },
    { pattern: /thanksgiving/gi, freq: 'YEARLY', interval: 1, bymonth: 11 },
    { pattern: /easter/gi, freq: 'YEARLY', interval: 1, bymonth: 4 },
    { pattern: /valentine/gi, freq: 'YEARLY', interval: 1, bymonth: 2, bymonthday: 14 },
    { pattern: /halloween/gi, freq: 'YEARLY', interval: 1, bymonth: 10, bymonthday: 31 },
    
    // Time-based patterns
    { pattern: /morning/gi, freq: 'DAILY', interval: 1, byhour: 9 },
    { pattern: /afternoon/gi, freq: 'DAILY', interval: 1, byhour: 14 },
    { pattern: /evening/gi, freq: 'DAILY', interval: 1, byhour: 18 },
    { pattern: /night/gi, freq: 'DAILY', interval: 1, byhour: 20 },
    { pattern: /lunch\s*time/gi, freq: 'DAILY', interval: 1, byhour: 12 },
    { pattern: /breakfast/gi, freq: 'DAILY', interval: 1, byhour: 8 },
    { pattern: /dinner/gi, freq: 'DAILY', interval: 1, byhour: 19 },
    
    // Frequency patterns
    { pattern: /once\s*per\s*day/gi, freq: 'DAILY', interval: 1 },
    { pattern: /twice\s*per\s*day/gi, freq: 'DAILY', interval: 1 },
    { pattern: /once\s*per\s*week/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /twice\s*per\s*week/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /once\s*per\s*month/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /twice\s*per\s*month/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /once\s*per\s*year/gi, freq: 'YEARLY', interval: 1 },
    { pattern: /twice\s*per\s*year/gi, freq: 'YEARLY', interval: 1 },
    
    // Business patterns
    { pattern: /business\s*day/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /work\s*day/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /working\s*day/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /office\s*day/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /school\s*day/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    { pattern: /weekday/gi, freq: 'WEEKLY', interval: 1, byweekday: 'MO,TU,WE,TH,FR' },
    
    // Special patterns
    { pattern: /as\s*needed/gi, freq: 'DAILY', interval: 1 },
    { pattern: /on\s*demand/gi, freq: 'DAILY', interval: 1 },
    { pattern: /when\s*required/gi, freq: 'DAILY', interval: 1 },
    { pattern: /when\s*needed/gi, freq: 'DAILY', interval: 1 },
    { pattern: /occasionally/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /sometimes/gi, freq: 'WEEKLY', interval: 1 },
    { pattern: /rarely/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /seldom/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /infrequently/gi, freq: 'MONTHLY', interval: 1 },
    { pattern: /sporadically/gi, freq: 'WEEKLY', interval: 1 }
];